### ISSUE TITLE
RFC: Built-in !count variable/directive

### ISSUE THREAD

**Issue by kestred** [jrgql/jrgql.github.io#5]
- Feature Name: builtin-count-directive

# Summary
[summary]: #summary

Add a new built-in variable/directive `"!count"` that can be used to get the
count of matching nodes (or the count of an array or nested query)

```json
{
  "name": "James",
  "?groups": {
    "!count": "*"
  }
}

[
  {
    "name": "James",
    "groups": [{
      "count(*)": 3,
    }]
  }
]
```

# Motivation
[motivation]: #motivation

This is a very commonly used grouping operation that is also supported by almost
all backend data stores (MongoDB, SQL, Neo4j, etc...).

While in the MongoDB case, a developer can just check the array length of the id
array to count ALL records, the same operation is more expensive in relational,
graph, and key/value databases.

Additionally, the count directive allows counting with Search terms and an
argument of what value to count (for counting non-null and non-absent values).

# Detailed design
[design]: #detailed-design

The key `"!count"` will be added as a new variable/directive.  The value of the
variable will be the field/property to count, with `*` being a special value
indicating all variables.

When the count directive is included in the query of a collection, an array will
still be returned, but with a single element which contains a `count(field)` key
and the resulting variable.

The value returned for that query/nested-query/subquery is an array with one
child which is an object with the key

### Usage examples

To count all users:

```json
{
  "!count": "*"
}

[
  {
    "count(*)": 4
  }
]
```

To count all users where the email is a `@gmail.com`:

```json
{
  "!count": "*",
  "email?": ".+@gmail.com$"
}

[
  {
    "count(*)": 0,
  }
]
```

To count users where boss is not null:

```json
{
  "!count": "boss"  
}

[
  {
    "count(boss)": 2
  }
]
```

### MongoDB driver implementation

1. If the value of `!count` is not `*` add a new key/value to the query where the
   key is the value of `count` and the value is the regexp `.*`

2. Remove the `!count` key from the query.

3. Use the MongoDB `count` API instead of the `find` API.

    ```js
    db.collection(type).count(query)
    ```

### Other notes

This design also allows other non-builtin aggregation methods to be implemented
as variables/directives depending on the backend driver.

The SQL `SUM` aggregation method is a good example:

```json
{
  "?payments": {
    "!count": "*",
    "!sum": "amount"
  }
}

[
  {
    "payments": [{
      "count(*)": 6,
      "sum(amount)": 275.10,
    }]
  }
]
```

**Comment by kestred** [comment]
After many iterations, the work I've done on graph APIs has branched away from the current spec. 
Since my use case now has largely different design goals from `jr`, I'll be closing this issue, so that it isn't sitting around without an owner to provide a rationale.

**Comment by Jamesgt** [comment]
I still like the idea and I want to implement it some time.
Is your work public? It would be nice to see what goals this project cannot fulfill, to make it more robust.
