### ISSUE TITLE
Question: What is the benefit of the actions "multiple calls" array syntax?

### ISSUE THREAD

**Issue by kestred** [jrgql/jrgql.github.io#6]
In keeping with the stated goal of keep jrGQL small (and IMO also making it easier to implement),  what is the benefit of supporting the following syntax for actions?

 ```json
{
  "!": [
      {
        "type.expand": [
          "district:String"
        ]
      },
      {
        "type.init": {
          "district": "Tarjan"
        }
      }
    ]
}
``` 

It seems like you can accomplish the same thing just by using the normal "multiple query" syntax:

```
[
  {
    "!": {
      "type.expand": [
          "district:String"
        ]
      }
  },
  {
    "!": {
      "type.init": {
        "district": "Tarjan"
      }
  }
]
```

**Comment by Jamesgt** [comment]
It was pretty easy to implement, so I've done it. This can be something that an actual implementation decides to have or not. So I should introduce a must have and a should have section when documenting the "language" itself.

**Comment by kestred** [comment]
Sounds good 👌 .
